- name: Validar e preparar ambiente
  hosts: nginx ec2 instances
  become: yes
  tasks:
    - name: Verificar se o Python está instalado
      command: which python3
      register: python_installed
      failed_when: python_installed.rc != 0

    - name: Atualizar pacotes
      apt:
        update_cache: yes
        upgrade: yes

