---
- name: Testar criação de arquivo
  hosts: localhost
  become: yes
  tasks:
    - name: Criar um arquivo de texto de teste
      ansible.builtin.copy:
        dest: /home/user14/Documents/teste.txt
        content: "Teste de criação de arquivo."
        mode: '0644'

 