- name: Create text files with content
  hosts: localhost
  become: yes
  vars:
    item_content: "Hey! seu playbook foi executado"
    dest_dir: /home/user14/Documents
    files: 
      - test.txt
      - test2.txt
  tasks:
    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory

    - name: Write content to files
      ansible.builtin.copy:
        content: "{{ item_content }}"
        dest: "{{ dest_dir }}{{ item }}"
      loop: "{{ files }}"
      loop_control:
        loop_var: item

        
