---
- name: Criar um arquivo simples no localhost
  hosts: meu localhost
  become: yes  # Usa privilégios elevados se necessário (por exemplo, para permissões de arquivos)
  tasks:
    - name: Criar um arquivo de texto
      ansible.builtin.copy:
        dest: /home/user14/arquivo_simples.txt
        content: |
          Este é um arquivo criado pelo Ansible.
        mode: '0644'
