---
- name: Criar e configurar um arquivo de texto
  hosts: localhost
  become: yes
  tasks:
    - name: Criar um diretório para o arquivo
      file:
        path: /home/user14/Documents
        state: directory

    - name: Criar um arquivo de texto
      copy:
        dest: /home/user14/Documents/arquivo.txt
        content: |
          Esta é uma linha de texto.
          Esta é outra linha de texto.
        mode: '0644'
 