---
- name: install Apache
  hosts: apache ec2 instances
  become: yes 
  tasks:
  - name: update dnf packages
    ansible.builtin.package:
      name: '*'
      state: latest


  - name: Update APT cache
    apt:
      update_cache: yes

      
  - name: install Apache 
    ansible.builtin.package:
      name: apache2
      state: present

  - name: Garantee apache is started  
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: true

  









