---
- name: Apache server installed
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
  become: yes
  tasks:
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest
  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started
